default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  host: localhost
development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: freemarket_sample_67d_database
  pool: 5
  username: root
  password:
  host: localhost
test:
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: freemarket_sample_67d_database_test
  pool: 5
  username: root
  password:
  host: localhost